baseURL: "https://davidpaulius.github.io/"
title: "David Paulius, Ph.D. | Personal Website"
pagination:
  pagerSize: 20
theme: PaperMod
copyright: "© 2025 David Paulius"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: "https://drive.google.com/file/d/18anG-rgWd6nU4ajJYlvwcPFUxxXIDz2b/view"
          weight: 1
        - name: Resume
          url: "https://drive.google.com/file/d/1tabAmFvz4KC_yAgRbN2dha_btvL4NsEg/view"
          weight: 2
        - name: News
          url: /news/
          weight: 3
        - name: Papers
          url: /papers/
          weight: 4
        - name: Academia
          url: /academia/
          weight: 5
        - name: Blog
          url: /blog/
          weight: 5
        - name: Etcetera
          url: /etcetera/
          weight: 5

params:
    description: "I am a postdoctoral researcher at Brown University, working with Profs. George Konidaris and Stefanie Tellex."
    author: David Paulius, Ph.D.
    DateFormat: "January 2006"
    defaultTheme: "auto"
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShareButtons: ["linkedin"]
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "Hi, I am David (dah-veed):"
          subtitle: "•	A roboticist from the Caribbean (<a href='https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis' target='_blank'>🇰🇳</a>). 🦾🏝️\
                    <br>\
                    •	A postdoctoral researcher at Brown University. 🎓🐻\
                    <br><br>\
                    <h4>Note: I am on the <u>job market</u>! Looking for research-related jobs. ;)</h4><br>\
                    <details>\
                    <br>\
                    <summary>Short Bio:</summary>\
                    <p style='text-align: justify; border-width: 3px; border-style: solid; padding: 20px;'>David Paulius (he/him) is a postdoctoral researcher in the <a href='http://irl.cs.brown.edu/' target='_blank'>Intelligent Robot Lab</a> at \
                    Brown University, working jointly with Professors <a href='https://cs.brown.edu/~gdk/' target='_blank'>George Konidaris</a> and <a href='https://h2r.cs.brown.edu/' target='_blank'>Stefanie Tellex</a>. \
                    Before joining Brown University, he was a postdoctoral researcher in the \
                    Human-centered Assistive Robotics (HCR) group at the Technical University of Munich, Germany. \
                    David received his PhD in Computer Science & Engineering from the University \
                    of South Florida, where he was advised by Professor Yu Sun and began his journey in \
                    robotics and AI. He received his BSc in Computer Science from the University of the \
                    Virgin Islands, St. Thomas, USVI. He was recognized as a <a href='https://sites.google.com/view/rsspioneers2022/' target='_blank'>Robotics: Science and \
                    Systems (RSS) Pioneer</a> in 2022. David is interested in enabling robots to solve complex \
                    goal-directed tasks in dynamic human environments by exploiting commonly available \
                    but unstructured world knowledge. His work explores the integration of classical \
                    planning and foundation models for long-term autonomy and generalization across \
                    robots, task settings, and domains.</p>\
                    </details><br>"
          imageUrl: "/imgs/profile.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: "Profile Picture of David Paulius"
          buttons:
            - name: "Latest News"
              url: /news/
            - name: "Recent Papers"
              url: /papers/
            # - name: "Academia"
            #   url: /academia/
            - name: "About Me"
              url: /etcetera/

    socialIcons:
        - name: "cv"
          url: "https://drive.google.com/file/d/18anG-rgWd6nU4ajJYlvwcPFUxxXIDz2b/view?usp=drive_link"
        - name: "gitHub"
          url: "https://github.com/davidpaulius"
        - name: "orcid"
          url: "https://orcid.org/0000-0002-7891-8749"
        - name: "googlescholar"
          url: "https://scholar.google.com/citations?user=aMxXkWkAAAAJ&hl=en"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/david-paulius/"
        - name: "letterboxd"
          url: "https://letterboxd.com/davi_duck/"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hidden: false
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "David Paulius, Ph.D."
      icon: /imgs/riegan.ico
      iconHeight: 28

    # stuff for fonts:
    google_fonts: [
      ["Fira Code", "400, 700"],
      ["Open Sans", "400, 400i, 700, 700i", "900"],
      ["IBM Plex Sans", "400", "500","400i", "500i", "900", "900i"],
      ["IBM Plex Serif", "400", "500", "900"],
      ["IBM Plex Mono", "400", "500","400i", "500i", "900", "900i"],
    ]
    fonts:
      heading:
        name: "IBM Plex Mono"
        weight: 900
        style: regular
      body:
        name: "IBM Plex Sans"
        weight: "400"
        style: "normal"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: monokai
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265

