baseURL: "https://davidpaulius.github.io/"
title: "David Paulius, Ph.D. | Personal Website"
pagination:
  pagerSize: 20
theme: PaperMod
copyright: "© 2026 David Paulius"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

taxonomies:
    tag: tags

menu:
    main:
        - name: "CV"
          url: "https://drive.google.com/file/d/18anG-rgWd6nU4ajJYlvwcPFUxxXIDz2b/view"
          weight: 1
        - name: Resume
          url: "https://drive.google.com/file/d/1tabAmFvz4KC_yAgRbN2dha_btvL4NsEg/view"
          weight: 2
        - name: News
          url: /news/
          weight: 3
        - name: Papers
          url: /papers/
          weight: 4
        # - name: Academia
        #   url: /academia/
        #   weight: 5
        - name: Blog
          url: /blog/
          weight: 5
        - name: Etcetera
          url: /etcetera/
          weight: 5

params:
    description: "I am a postdoctoral researcher at Brown University, working with Profs. George Konidaris and Stefanie Tellex."
    author: David Paulius, Ph.D.
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShareButtons: ["linkedin", "whatsapp"]
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "<div title='Pronounced \"dah-veed/dah-vid paw-lee-us\"'>Hi, I am David Paulius:</div>"
          # Subtitle content is in layouts/partials/profile_subtitle.html
          imageUrl: "/imgs/profile_pics/Paulius2026.jpg"
          imageClickable: true
          fullImageCaption: "Taken at <a href='https://maps.app.goo.gl/fBha2A1EARXgJaw49'>Cockleshell Bay, St. Kitts, W.I.</a>."
          imageWidth: 220
          imageHeight: 220
          #imageTitle: "Headshot of David Paulius. David is wearing a dapper black suit with a red tie in front of a 400-year old Saman tree at Romney Manor, St. Kitts."
          buttons:
            - name: "Latest News"
              url: /news/
            - name: "Recent Papers"
              url: /papers/
            # - name: "Academia"
            #   url: /academia/
            - name: "About Me"
              url: /etcetera/

    socialIcons:
        - name: "cv"
          url: "https://drive.google.com/file/d/18anG-rgWd6nU4ajJYlvwcPFUxxXIDz2b/view?usp=drive_link"
        - name: "gitHub"
          url: "https://github.com/davidpaulius"
        - name: "orcid"
          url: "https://orcid.org/0000-0002-7891-8749"
        - name: "googlescholar"
          url: "https://scholar.google.com/citations?user=aMxXkWkAAAAJ&hl=en"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/davidpaulius/"
        - name: "letterboxd"
          url: "https://letterboxd.com/davi_duck/"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hidden: false
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "David Paulius, Ph.D."
      icon: /imgs/riegan.ico
      iconHeight: 28

    # stuff for fonts:
    google_fonts: [
      ["Fira Code", "400", "700"],
      ["Open Sans", "400", "400i", "700", "700i", "900"],
      ["IBM Plex Sans", "400", "500", "400i", "500i", "900", "900i"],
      ["IBM Plex Serif", "400", "500", "900"],
      ["IBM Plex Mono", "400", "500","400i", "500i", "900", "900i"],
      ["Noto Sans", "400", "500", "400i", "500i", "900", "900i"],
      ["Noto Serif", "400", "500", "900"],
      ["Inter Tight", "400", "500", "600", "700", "800", "900"],
      ["Inter", "400", "500", "600", "700", "800", "900"],
      ["Playfair Display", "400", "500", "600", "700", "800", "900"],
    ]
    fonts:
      heading:
        name: "Inter Tight"
        weight: "600"
        style: regular
      body:
        name: "Inter Tight"
        weight: "400"
        style: "regular"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: monokai
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265

